name:                wordru
version:             0.1.0.0
github:              "githubuser/wordru"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wordru#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- text
- time
- aeson
- mtl
- attoparsec
- string-conversions
- wai
- warp
- directory
- blaze-markup
- blaze-html
- base-compat-batteries
- bytestring
- http-media
- lucid
- hedis
- uuid
- transformers
- file-embed
- random
- wai-cors

library:
  source-dirs: src

executables:
  wordru-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordru

tests:
  wordru-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordru
